// Switch and steering input circuitry for Atari Super Bug.
// Hand-written Verilog port of source/inputs.vhd (James Sweet, 2018).
// Replaces an X-HDL auto-translation with a malformed sensitivity list
// on the steering quadrature flip-flop.
//
// `input` is a Verilog keyword, so the module is named input_xhdl0 to
// match the existing instantiation surface generated by the translator.

`default_nettype none

module input_xhdl0(
    input  wire [7:0] DIP_Sw,
    input  wire       Coin1_n,
    input  wire       Coin2_n,
    input  wire       Start_n,
    input  wire       TrackSel_n,
    input  wire       Gas_n,
    input  wire       Gear1_n,
    input  wire       Gear2_n,
    input  wire       Gear3_n,
    input  wire       Test_n,
    input  wire       HScoreRes_n,
    input  wire       Slam_n,
    input  wire       Steering1A_n,
    input  wire       Steering1B_n,
    input  wire       SteerReset_n,
    input  wire       In1_n,
    input  wire       Opt_n,
    input  wire       SkidIn_n,
    input  wire       CrashIn_n,
    input  wire [2:0] Adr,
    output wire [7:0] DBus
);

    wire Steering1A = ~Steering1A_n;

    // 7474 quadrature decoder (H10/J10) -- async clear, posedge B
    reg SteerFlag;
    reg SteerDir;
    always @(posedge Steering1B_n or negedge SteerReset_n) begin
        if (~SteerReset_n) begin
            SteerFlag <= 1'b0;
            SteerDir  <= 1'b0;
        end else begin
            SteerFlag <= 1'b1;
            SteerDir  <= Steering1A;
        end
    end

    // 74153 mux at F9 (active-low inputs, output is inverted sense)
    reg InputMux1;
    always @* begin
        case (Adr)
            3'b000: InputMux1 = ~TrackSel_n;
            3'b001: InputMux1 = ~CrashIn_n;
            3'b010: InputMux1 = ~Start_n;
            3'b011: InputMux1 = ~Coin2_n;
            3'b100: InputMux1 = ~Coin1_n;
            3'b101: InputMux1 = ~SteerFlag;
            3'b110: InputMux1 = ~Gear1_n;
            3'b111: InputMux1 = ~Gear3_n;
            default: InputMux1 = 1'b1;
        endcase
    end

    // 74153 mux at E9 (note flipped address ordering vs F9)
    reg InputMux2;
    always @* begin
        case (Adr)
            3'b000: InputMux2 = ~Gear2_n;
            3'b100: InputMux2 = ~Gas_n;
            3'b010: InputMux2 = ~SteerDir;
            3'b110: InputMux2 = ~HScoreRes_n;
            3'b001: InputMux2 = 1'b0;
            3'b101: InputMux2 = ~Test_n;
            3'b011: InputMux2 = ~SkidIn_n;
            3'b111: InputMux2 = ~Slam_n;
            default: InputMux2 = 1'b1;
        endcase
    end

    // 74153 dual mux at C6 (DIP switches, paired)
    reg [1:0] DIP_Mux;
    always @* begin
        case (Adr[1:0])
            2'b00: DIP_Mux = {DIP_Sw[7], DIP_Sw[6]};
            2'b01: DIP_Mux = {DIP_Sw[5], DIP_Sw[4]};
            2'b10: DIP_Mux = {DIP_Sw[3], DIP_Sw[2]};
            2'b11: DIP_Mux = {DIP_Sw[1], DIP_Sw[0]};
            default: DIP_Mux = 2'b11;
        endcase
    end

    assign DBus = (~In1_n) ? {InputMux1, 6'b111111, InputMux2}
                : (~Opt_n) ? {6'b111111, DIP_Mux}
                :            8'hFF;

endmodule

`default_nettype wire
