// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vemu.h for the primary calling header

#ifndef VERILATED_VEMU___024ROOT_H_
#define VERILATED_VEMU___024ROOT_H_  // guard

#include "verilated.h"


class Vemu__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vemu___024root final {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk_sys,0,0);
        VL_IN8(service_mode,0,0);
        VL_IN8(reset,0,0);
        VL_IN8(soft_reset,0,0);
        VL_IN8(menu,0,0);
        VL_IN8(adam,0,0);
        VL_IN8(paddle_0,7,0);
        VL_IN8(paddle_1,7,0);
        VL_IN8(paddle_2,7,0);
        VL_IN8(paddle_3,7,0);
        VL_IN8(paddle_4,7,0);
        VL_IN8(paddle_5,7,0);
        VL_OUT8(VGA_R,7,0);
        VL_OUT8(VGA_G,7,0);
        VL_OUT8(VGA_B,7,0);
        VL_OUT8(VGA_HS,0,0);
        VL_OUT8(VGA_VS,0,0);
        VL_OUT8(VGA_HB,0,0);
        VL_OUT8(VGA_VB,0,0);
        VL_OUT8(CE_PIXEL,0,0);
        VL_OUT8(dbg_opcode,7,0);
        VL_OUT8(dbg_din,7,0);
        VL_OUT8(dbg_op_fetch,0,0);
        VL_OUT8(dbg_acca,7,0);
        VL_OUT8(dbg_accb,7,0);
        VL_OUT8(dbg_cc,7,0);
        VL_IN8(ioctl_download,0,0);
        VL_IN8(ioctl_wr,0,0);
        VL_IN8(ioctl_dout,7,0);
        VL_IN8(ioctl_index,7,0);
        VL_OUT8(ioctl_wait,0,0);
        VL_IN8(sd_buff_dout,7,0);
        VL_IN8(sd_buff_wr,0,0);
        VL_IN8(img_readonly,0,0);
        CData/*0:0*/ emu__DOT__UART_CTS;
        CData/*0:0*/ emu__DOT__UART_RTS;
        CData/*0:0*/ emu__DOT__UART_RXD;
        CData/*0:0*/ emu__DOT__UART_TXD;
        CData/*0:0*/ emu__DOT__UART_DTR;
        CData/*0:0*/ emu__DOT__UART_DSR;
        CData/*0:0*/ emu__DOT__btn_right;
        CData/*0:0*/ emu__DOT__btn_left;
        CData/*0:0*/ emu__DOT__btn_gas;
        CData/*0:0*/ emu__DOT__btn_gearup;
        CData/*0:0*/ emu__DOT__btn_geardown;
        CData/*0:0*/ emu__DOT__btn_nexttrack;
        CData/*0:0*/ emu__DOT__btn_one_player;
        CData/*0:0*/ emu__DOT__btn_two_players;
        CData/*0:0*/ emu__DOT__btn_start_1;
        CData/*0:0*/ emu__DOT__btn_coin_1;
        CData/*0:0*/ emu__DOT__btn_coin_2;
        CData/*0:0*/ emu__DOT__m_gas;
        CData/*0:0*/ emu__DOT__m_next_track;
        CData/*0:0*/ emu__DOT__m_start1;
        CData/*0:0*/ emu__DOT__m_coin;
        CData/*1:0*/ emu__DOT__steer;
        CData/*0:0*/ emu__DOT__gear1;
        CData/*0:0*/ emu__DOT__gear2;
        CData/*0:0*/ emu__DOT__gear3;
        CData/*0:0*/ emu__DOT__vsync;
        CData/*0:0*/ emu__DOT__audio;
        CData/*0:0*/ emu__DOT__lamp;
        CData/*0:0*/ emu__DOT__lamp2;
        CData/*0:0*/ emu__DOT____Vcellinp__superbug__Steer_1B_I;
    };
    struct {
        CData/*0:0*/ emu__DOT____Vcellinp__superbug__Start_I;
        CData/*0:0*/ emu__DOT__clk_6;
        CData/*0:0*/ emu__DOT__locked;
        CData/*7:0*/ emu__DOT__vid_mono;
        CData/*1:0*/ emu__DOT__sprint_vid;
        CData/*0:0*/ emu__DOT__unnamedblk1__DOT__old_state;
        CData/*3:0*/ emu__DOT__steer1__DOT__state;
        CData/*2:0*/ emu__DOT__gearshift1__DOT__gear;
        CData/*0:0*/ emu__DOT__gearshift1__DOT__unnamedblk1__DOT__old_gear_up;
        CData/*0:0*/ emu__DOT__gearshift1__DOT__unnamedblk1__DOT__old_gear_down;
        CData/*0:0*/ emu__DOT__superbug__DOT__HSRes_I;
        CData/*0:0*/ emu__DOT__superbug__DOT__Phi2;
        CData/*0:0*/ emu__DOT__superbug__DOT__PCC1;
        CData/*0:0*/ emu__DOT__superbug__DOT__PCC2;
        CData/*0:0*/ emu__DOT__superbug__DOT__PFWndo;
        CData/*0:0*/ emu__DOT__superbug__DOT__Flash;
        CData/*0:0*/ emu__DOT__superbug__DOT__CarVideo;
        CData/*0:0*/ emu__DOT__superbug__DOT__VMA;
        CData/*0:0*/ emu__DOT__superbug__DOT__CrashIn_n;
        CData/*0:0*/ emu__DOT__superbug__DOT__SkidIn_n;
        CData/*0:0*/ emu__DOT__superbug__DOT__Attract;
        CData/*0:0*/ emu__DOT__superbug__DOT__SteerReset_n;
        CData/*2:0*/ emu__DOT__superbug__DOT____Vcellinp__ControlInputs__Adr;
        CData/*7:0*/ emu__DOT__superbug__DOT__Vid_sync__DOT__v_counter;
        CData/*3:0*/ emu__DOT__superbug__DOT__Vid_sync__DOT__sync_bus;
        CData/*3:0*/ emu__DOT__superbug__DOT__Vid_sync__DOT__sync_reg;
        CData/*0:0*/ emu__DOT__superbug__DOT__Vid_sync__DOT__vblank_int;
        CData/*0:0*/ emu__DOT__superbug__DOT__Vid_sync__DOT__hblank_int;
        CData/*0:0*/ emu__DOT__superbug__DOT__Vid_sync__DOT__hsync_int;
        CData/*0:0*/ emu__DOT__superbug__DOT__Vid_sync__DOT__hsync_reset;
        CData/*7:0*/ emu__DOT__superbug__DOT__Vid_sync__DOT__prom_address;
        CData/*0:0*/ emu__DOT__superbug__DOT__Vid_sync__DOT__prev_H32;
        CData/*0:0*/ emu__DOT__superbug__DOT__Vid_sync__DOT__prev_H8;
        CData/*0:0*/ emu__DOT__superbug__DOT__Vid_sync__DOT__prev_H256_n;
        CData/*0:0*/ emu__DOT__superbug__DOT__Vid_sync__DOT__prev_hblank_int;
        CData/*0:0*/ emu__DOT__superbug__DOT__Vid_sync__DOT__prev_hsync_int;
        CData/*0:0*/ emu__DOT__superbug__DOT__CPU__DOT__Reset;
        CData/*0:0*/ emu__DOT__superbug__DOT__CPU__DOT__H2;
        CData/*7:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU_Din;
        CData/*0:0*/ emu__DOT__superbug__DOT__CPU__DOT__RAMwe;
        CData/*7:0*/ emu__DOT__superbug__DOT__CPU__DOT__ROM1_Dout;
        CData/*7:0*/ emu__DOT__superbug__DOT__CPU__DOT__ROM2_Dout;
        CData/*7:0*/ emu__DOT__superbug__DOT__CPU__DOT__ROM3_Dout;
        CData/*0:0*/ emu__DOT__superbug__DOT__CPU__DOT__IRQ_n;
        CData/*0:0*/ emu__DOT__superbug__DOT__CPU__DOT__SysEn;
        CData/*0:0*/ emu__DOT__superbug__DOT__CPU__DOT__rw;
        CData/*0:0*/ emu__DOT__superbug__DOT__CPU__DOT__IO_Wr;
        CData/*0:0*/ emu__DOT__superbug__DOT__CPU__DOT__Out2_n;
        CData/*0:0*/ emu__DOT__superbug__DOT__CPU__DOT__nmi;
        CData/*0:0*/ emu__DOT__superbug__DOT__CPU__DOT__prev_V16;
        CData/*3:0*/ emu__DOT__superbug__DOT__CPU__DOT____Vcellout__M1__q;
        CData/*3:0*/ emu__DOT__superbug__DOT__CPU__DOT____Vcellout__N1__q;
        CData/*0:0*/ emu__DOT__superbug__DOT__CPU__DOT____VdfgRegularize_h17664f61_0_0;
        CData/*0:0*/ emu__DOT__superbug__DOT__CPU__DOT____VdfgRegularize_h17664f61_0_1;
        CData/*0:0*/ emu__DOT__superbug__DOT__CPU__DOT____VdfgRegularize_h17664f61_0_2;
        CData/*0:0*/ emu__DOT__superbug__DOT__CPU__DOT____VdfgRegularize_h17664f61_0_3;
        CData/*0:0*/ emu__DOT__superbug__DOT__CPU__DOT____VdfgRegularize_h17664f61_0_11;
        CData/*7:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__op_code;
        CData/*7:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__acca;
        CData/*7:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__accb;
        CData/*7:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__cc;
        CData/*1:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__iv;
        CData/*0:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__nmi_req;
        CData/*0:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__nmi_ack;
    };
    struct {
        CData/*5:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__state;
        CData/*5:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__next_state;
        CData/*2:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__pc_ctrl;
        CData/*2:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__ea_ctrl;
        CData/*1:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__op_ctrl;
        CData/*2:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__md_ctrl;
        CData/*2:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__acca_ctrl;
        CData/*1:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__accb_ctrl;
        CData/*2:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__ix_ctrl;
        CData/*1:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__cc_ctrl;
        CData/*1:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__sp_ctrl;
        CData/*2:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__iv_ctrl;
        CData/*2:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__left_ctrl;
        CData/*1:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__right_ctrl;
        CData/*5:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__alu_ctrl;
        CData/*2:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__addr_ctrl;
        CData/*3:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__dout_ctrl;
        CData/*1:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__nmi_ctrl;
        CData/*7:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__cc_out;
        CData/*0:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__carry_in;
        CData/*7:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__daa_reg;
        CData/*0:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__valid_lo;
        CData/*0:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__valid_hi;
        CData/*0:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__mul_bit;
        CData/*0:0*/ emu__DOT__superbug__DOT__Vid_mixer__DOT__Pfld;
        CData/*0:0*/ emu__DOT__superbug__DOT__Vid_mixer__DOT__CompBlank;
        CData/*0:0*/ emu__DOT__superbug__DOT__Vid_mixer__DOT__FlashWndo;
        CData/*2:0*/ emu__DOT__superbug__DOT__Vid_mixer__DOT__VideoLatch;
        CData/*7:0*/ emu__DOT__superbug__DOT__Alpha__DOT__BD;
        CData/*0:0*/ emu__DOT__superbug__DOT__Alpha__DOT__Sys_en;
        CData/*0:0*/ emu__DOT__superbug__DOT__Alpha__DOT__A_NVideo;
        CData/*6:0*/ emu__DOT__superbug__DOT__Alpha__DOT__RAM_Addr;
        CData/*7:0*/ emu__DOT__superbug__DOT__Alpha__DOT__RAM_Dout2;
        CData/*7:0*/ emu__DOT__superbug__DOT__Alpha__DOT__RAM_Dout;
        CData/*0:0*/ emu__DOT__superbug__DOT__Alpha__DOT__Mux_select;
        CData/*3:0*/ emu__DOT__superbug__DOT__Alpha__DOT__M3_Dout;
        CData/*3:0*/ emu__DOT__superbug__DOT__Alpha__DOT__N3_Dout;
        CData/*3:0*/ emu__DOT__superbug__DOT__Alpha__DOT__ShiftData;
        CData/*0:0*/ emu__DOT__superbug__DOT__Car__DOT__CarRot_n;
        CData/*3:0*/ emu__DOT__superbug__DOT__Car__DOT__CarROM_Dout;
        CData/*0:0*/ emu__DOT__superbug__DOT__Car__DOT__CarEna_n;
        CData/*0:0*/ emu__DOT__superbug__DOT__Car__DOT__R1;
        CData/*0:0*/ emu__DOT__superbug__DOT__Car__DOT__R0;
        CData/*0:0*/ emu__DOT__superbug__DOT__Car__DOT__V16g;
        CData/*0:0*/ emu__DOT__superbug__DOT__Car__DOT__V8g;
        CData/*0:0*/ emu__DOT__superbug__DOT__Car__DOT__V4g;
        CData/*0:0*/ emu__DOT__superbug__DOT__Car__DOT__V2g;
        CData/*0:0*/ emu__DOT__superbug__DOT__Car__DOT__V1g;
        CData/*0:0*/ emu__DOT__superbug__DOT__Car__DOT__H16g;
        CData/*0:0*/ emu__DOT__superbug__DOT__Car__DOT__H8g;
        CData/*0:0*/ emu__DOT__superbug__DOT__Car__DOT__H4g;
        CData/*0:0*/ emu__DOT__superbug__DOT__Car__DOT__H2g;
        CData/*0:0*/ emu__DOT__superbug__DOT__Car__DOT__H1g;
        CData/*0:0*/ emu__DOT__superbug__DOT__Car__DOT__M7Qa;
        CData/*0:0*/ emu__DOT__superbug__DOT__Car__DOT__M7Qb;
        CData/*0:0*/ emu__DOT__superbug__DOT__Car__DOT__BD2_Sel;
        CData/*0:0*/ emu__DOT__superbug__DOT__Car__DOT__BD3_Sel;
        CData/*0:0*/ emu__DOT__superbug__DOT__Car__DOT__BD4_Sel;
        CData/*1:0*/ emu__DOT__superbug__DOT__Car__DOT__R_Sel;
        CData/*0:0*/ emu__DOT__superbug__DOT__Car__DOT__prev_H16;
        CData/*0:0*/ emu__DOT__superbug__DOT__Car__DOT__prev_V8;
        CData/*0:0*/ emu__DOT__superbug__DOT__Car__DOT__prev_CarRot_n;
        CData/*3:0*/ emu__DOT__superbug__DOT__Playfield__DOT__E5_Dout;
        CData/*3:0*/ emu__DOT__superbug__DOT__Playfield__DOT__F5_Dout;
    };
    struct {
        CData/*3:0*/ emu__DOT__superbug__DOT__Playfield__DOT__H5_Dout;
        CData/*7:0*/ emu__DOT__superbug__DOT__Playfield__DOT__PD;
        CData/*7:0*/ emu__DOT__superbug__DOT__Playfield__DOT__PVP;
        CData/*7:0*/ emu__DOT__superbug__DOT__Playfield__DOT__PHP;
        CData/*7:0*/ emu__DOT__superbug__DOT__Playfield__DOT__PF_RAM_Adr;
        CData/*7:0*/ emu__DOT__superbug__DOT__Playfield__DOT__PFRAM_Din;
        CData/*0:0*/ emu__DOT__superbug__DOT__Playfield__DOT__PF_Wren;
        CData/*0:0*/ emu__DOT__superbug__DOT__Playfield__DOT__PfldRAM;
        CData/*0:0*/ emu__DOT__superbug__DOT__Playfield__DOT__PD_en;
        CData/*0:0*/ emu__DOT__superbug__DOT__Playfield__DOT__CrashCode;
        CData/*0:0*/ emu__DOT__superbug__DOT__Playfield__DOT__SkidCode_n;
        CData/*0:0*/ emu__DOT__superbug__DOT__Playfield__DOT__PfCarVid;
        CData/*0:0*/ emu__DOT__superbug__DOT__Playfield__DOT__Arrow_n;
        CData/*3:0*/ emu__DOT__superbug__DOT__Playfield__DOT__VidShift;
        CData/*0:0*/ emu__DOT__superbug__DOT__Playfield__DOT__LoadPd;
        CData/*0:0*/ emu__DOT__superbug__DOT__Playfield__DOT__PfWndo_n;
        CData/*0:0*/ emu__DOT__superbug__DOT__Playfield__DOT__Window_en;
        CData/*3:0*/ emu__DOT__superbug__DOT__Playfield__DOT____Vcellout__E6__q;
        CData/*3:0*/ emu__DOT__superbug__DOT__Playfield__DOT____Vcellout__F6__q;
        CData/*0:0*/ emu__DOT__superbug__DOT__Playfield__DOT__prev_VBlank_arrow;
        CData/*0:0*/ emu__DOT__superbug__DOT__Playfield__DOT__prev_H8_pfwndo;
        CData/*0:0*/ emu__DOT__superbug__DOT__ControlInputs__DOT__Coin1;
        CData/*0:0*/ emu__DOT__superbug__DOT__ControlInputs__DOT__Coin2;
        CData/*0:0*/ emu__DOT__superbug__DOT__ControlInputs__DOT__SteerDir;
        CData/*0:0*/ emu__DOT__superbug__DOT__ControlInputs__DOT__SteerFlag;
        CData/*0:0*/ emu__DOT__superbug__DOT__ControlInputs__DOT__InputMux1;
        CData/*0:0*/ emu__DOT__superbug__DOT__ControlInputs__DOT__InputMux2;
        CData/*1:0*/ emu__DOT__superbug__DOT__ControlInputs__DOT__DIP_Mux;
        CData/*0:0*/ __VdfgRegularize_h4af1c392_0_0;
        CData/*0:0*/ __VdfgRegularize_h4af1c392_0_1;
        CData/*7:0*/ __Vdly__emu__DOT__superbug__DOT__Vid_sync__DOT__v_counter;
        CData/*3:0*/ __Vdly__emu__DOT__superbug__DOT__Vid_sync__DOT__sync_bus;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__emu__DOT__clk_6__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk_sys__0;
        CData/*7:0*/ __Vtrigprevexpr___TOP__emu__DOT__superbug__DOT__Vid_sync__DOT__prom_address__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__emu__DOT__superbug__DOT__CPU__DOT__H2__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__emu__DOT__superbug__DOT__CPU__DOT__Out2_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__emu__DOT__superbug__DOT__Phi2__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__emu__DOT__superbug__DOT__Car__DOT__CarEna_n__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__emu__DOT__superbug__DOT__Car__DOT__CarROM_Dout__0;
        CData/*1:0*/ __Vtrigprevexpr___TOP__emu__DOT__superbug__DOT__Car__DOT__R_Sel__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__emu__DOT__superbug__DOT__Vid_sync__DOT__hsync_int__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__emu__DOT____Vcellinp__superbug__Steer_1B_I__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__emu__DOT__superbug__DOT__SteerReset_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__emu__DOT____Vcellinp__superbug__Start_I__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__emu__DOT__gear1__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__emu__DOT__gear3__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__emu__DOT__m_next_track__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__emu__DOT__superbug__DOT__ControlInputs__DOT__Coin1__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__emu__DOT__superbug__DOT__ControlInputs__DOT__Coin2__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__emu__DOT__superbug__DOT__ControlInputs__DOT__SteerFlag__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__emu__DOT__superbug__DOT__CrashIn_n__0;
        CData/*2:0*/ __Vtrigprevexpr___TOP__emu__DOT__superbug__DOT____Vcellinp__ControlInputs__Adr__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__emu__DOT__gear2__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__emu__DOT__m_gas__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__emu__DOT__superbug__DOT__ControlInputs__DOT__SteerDir__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__emu__DOT__superbug__DOT__HSRes_I__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__emu__DOT__superbug__DOT__SkidIn_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__service_mode__0;
        CData/*0:0*/ __VactDidInit;
        VL_IN16(joystick_l_analog_0,15,0);
        VL_IN16(joystick_l_analog_1,15,0);
    };
    struct {
        VL_IN16(joystick_l_analog_2,15,0);
        VL_IN16(joystick_l_analog_3,15,0);
        VL_IN16(joystick_l_analog_4,15,0);
        VL_IN16(joystick_l_analog_5,15,0);
        VL_IN16(joystick_r_analog_0,15,0);
        VL_IN16(joystick_r_analog_1,15,0);
        VL_IN16(joystick_r_analog_2,15,0);
        VL_IN16(joystick_r_analog_3,15,0);
        VL_IN16(joystick_r_analog_4,15,0);
        VL_IN16(joystick_r_analog_5,15,0);
        VL_IN16(spinner_0,8,0);
        VL_IN16(spinner_1,8,0);
        VL_IN16(spinner_2,8,0);
        VL_IN16(spinner_3,8,0);
        VL_IN16(spinner_4,8,0);
        VL_IN16(spinner_5,8,0);
        VL_IN16(ps2_key,10,0);
        VL_IN16(ps2_mouse_ext,15,0);
        VL_OUT16(AUDIO_L,15,0);
        VL_OUT16(AUDIO_R,15,0);
        VL_OUT16(dbg_pc,15,0);
        VL_OUT16(dbg_addr,15,0);
        VL_OUT16(sd_rd,9,0);
        VL_OUT16(sd_wr,9,0);
        VL_IN16(sd_ack,9,0);
        VL_IN16(sd_buff_addr,8,0);
        VL_IN16(img_mounted,9,0);
        SData/*15:0*/ emu__DOT__joy;
        SData/*15:0*/ emu__DOT__superbug__DOT__CPU_Adr;
        SData/*9:0*/ emu__DOT__superbug__DOT__Vid_sync__DOT__h_counter;
        SData/*15:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__xreg;
        SData/*15:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__sp;
        SData/*15:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__ea;
        SData/*15:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__pc;
        SData/*15:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__md;
        SData/*15:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__left;
        SData/*15:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__right;
        SData/*15:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__out_alu;
        SData/*15:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__pc_base;
        SData/*15:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__ea_off;
        SData/*15:0*/ emu__DOT__superbug__DOT__CPU__DOT__CPU__DOT__ea_base;
        SData/*9:0*/ emu__DOT__superbug__DOT__Alpha__DOT__rom_m3_addr;
        SData/*9:0*/ emu__DOT__superbug__DOT__Playfield__DOT__PFROM_Adr;
        SData/*9:0*/ __Vdly__emu__DOT__superbug__DOT__Vid_sync__DOT__h_counter;
        VL_IN(joystick_0,31,0);
        VL_IN(joystick_1,31,0);
        VL_IN(joystick_2,31,0);
        VL_IN(joystick_3,31,0);
        VL_IN(joystick_4,31,0);
        VL_IN(joystick_5,31,0);
        VL_IN(ps2_mouse,24,0);
        VL_IN(ioctl_addr,24,0);
        IData/*31:0*/ emu__DOT__steer1__DOT__unnamedblk1__DOT__count;
        IData/*31:0*/ emu__DOT__superbug__DOT__Playfield__DOT__pf_write_count;
        IData/*31:0*/ __VactIterCount;
        VL_IN64(timestamp,32,0);
        VL_IN64(img_size,63,0);
        VL_OUT(sd_lba[2],31,0);
        VL_OUT8(sd_buff_din[2],7,0);
        VlUnpacked<IData/*31:0*/, 2> emu__DOT__sd_lba;
        VlUnpacked<CData/*7:0*/, 2> emu__DOT__sd_buff_din;
        VlUnpacked<CData/*3:0*/, 256> emu__DOT__superbug__DOT__CPU__DOT__M1__DOT__mem;
        VlUnpacked<CData/*3:0*/, 256> emu__DOT__superbug__DOT__CPU__DOT__N1__DOT__mem;
        VlUnpacked<CData/*7:0*/, 2048> emu__DOT__superbug__DOT__CPU__DOT__D1__DOT__mem;
    };
    struct {
        VlUnpacked<CData/*7:0*/, 2048> emu__DOT__superbug__DOT__CPU__DOT__C1__DOT__mem;
        VlUnpacked<CData/*7:0*/, 2048> emu__DOT__superbug__DOT__CPU__DOT__A1__DOT__mem;
        VlUnpacked<CData/*7:0*/, 128> emu__DOT__superbug__DOT__Alpha__DOT__P3_RAM__DOT__mem;
        VlUnpacked<CData/*3:0*/, 1024> emu__DOT__superbug__DOT__Alpha__DOT__M3_ROM__DOT__mem;
        VlUnpacked<CData/*3:0*/, 1024> emu__DOT__superbug__DOT__Alpha__DOT__N3_ROM__DOT__mem;
        VlUnpacked<CData/*3:0*/, 1024> emu__DOT__superbug__DOT__Car__DOT__K6__DOT__mem;
        VlUnpacked<CData/*3:0*/, 1024> emu__DOT__superbug__DOT__Playfield__DOT__E5__DOT__mem;
        VlUnpacked<CData/*3:0*/, 1024> emu__DOT__superbug__DOT__Playfield__DOT__F5__DOT__mem;
        VlUnpacked<CData/*3:0*/, 1024> emu__DOT__superbug__DOT__Playfield__DOT__H5__DOT__mem;
        VlUnpacked<CData/*3:0*/, 256> emu__DOT__superbug__DOT__Playfield__DOT__E6__DOT__mem;
        VlUnpacked<CData/*3:0*/, 256> emu__DOT__superbug__DOT__Playfield__DOT__F6__DOT__mem;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
        VlUnpacked<CData/*0:0*/, 17> __Vm_traceActivity;
    };

    // INTERNAL VARIABLES
    Vemu__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    Vemu___024root(Vemu__Syms* symsp, const char* namep);
    ~Vemu___024root();
    VL_UNCOPYABLE(Vemu___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
